name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use Node.js 10.24.1
        uses: actions/setup-node@v1
        with:
          node-version: '10.24.1'


      - name: Install npm dependencies
        run: npm ci

      - name: Run NG lint
        run: npm run lint

      - name: Run NG server
        run: npm run start & sleep 10

      - name: Run tests
        run: npm run test:integration
