name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm ci

      - name: Run NG lint
        run: npm run lint

      - name: Run NG server
        run: npm run start & sleep 10

      - name: Run tests
        run: npm run test:integration
